print("Hey,GitHub. You EROR?")
print("I'm ok!")
print("Hey,zerocoder. You Ok?")
print("I'm ok!")print("Hey,zerocoder. You Ok?")
print("I'm ok!")
print("Hey,zerocoder. You Ok?")
print("I'm ok!")print("Hey,zerocoder. You Ok?")
print("I'm ok!")